export default {
  ENUMS: {
    UI: {},
    COLOUR: {
      GREY: '#494949',
      WHITE: 'white',
    },
  },
  URL: {
    github: 'https://github.com/Beadsley/Covid-19-webapp',
  },
  mockdata: [
    {
      state: 'AK',
      deaths: 10,
      last3daysDeaths: null,
      hospitalizedCurrently: 8,
      name: 'Alaska',
      recovered: 318,
    },
    {
      state: 'AL',
      deaths: 388,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Alabama',
      recovered: null,
    },
    {
      state: 'AR',
      deaths: 88,
      last3daysDeaths: null,
      hospitalizedCurrently: 64,
      name: 'Arkansas',
      recovered: 2968,
    },
    {
      state: 'AS',
      deaths: 0,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'American Samoa',
      recovered: null,
    },
    {
      state: 'AZ',
      deaths: 532,
      last3daysDeaths: null,
      hospitalizedCurrently: 739,
      name: 'Arizona',
      recovered: 2684,
    },
    {
      state: 'CA',
      deaths: 2678,
      last3daysDeaths: null,
      hospitalizedCurrently: 4538,
      name: 'California',
      recovered: null,
    },
    {
      state: 'CO',
      deaths: 960,
      last3daysDeaths: null,
      hospitalizedCurrently: 790,
      name: 'Colorado',
      recovered: 2974,
    },
    {
      state: 'CT',
      deaths: 2932,
      last3daysDeaths: null,
      hospitalizedCurrently: 1301,
      name: 'Connecticut',
      recovered: 5413,
    },
    {
      state: 'DC',
      deaths: 311,
      last3daysDeaths: null,
      hospitalizedCurrently: 447,
      name: 'District Of Columbia',
      recovered: 879,
    },
    {
      state: 'DE',
      deaths: 221,
      last3daysDeaths: null,
      hospitalizedCurrently: 288,
      name: 'Delaware',
      recovered: 2450,
    },
    {
      state: 'FL',
      deaths: 1785,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Florida',
      recovered: null,
    },
    {
      state: 'GA',
      deaths: 1400,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Georgia',
      recovered: null,
    },
    {
      state: 'GU',
      deaths: 5,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Guam',
      recovered: 124,
    },
    {
      state: 'HI',
      deaths: 17,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Hawaii',
      recovered: 566,
    },
    {
      state: 'IA',
      deaths: 252,
      last3daysDeaths: null,
      hospitalizedCurrently: 402,
      name: 'Iowa',
      recovered: 5011,
    },
    {
      state: 'ID',
      deaths: 67,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Idaho',
      recovered: 1442,
    },
    {
      state: 'IL',
      deaths: 3349,
      last3daysDeaths: null,
      hospitalizedCurrently: 4739,
      name: 'Illinois',
      recovered: null,
    },
    {
      state: 'IN',
      deaths: 1490,
      last3daysDeaths: null,
      hospitalizedCurrently: 1361,
      name: 'Indiana',
      recovered: null,
    },
    {
      state: 'KS',
      deaths: 157,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Kansas',
      recovered: 350,
    },
    {
      state: 'KY',
      deaths: 298,
      last3daysDeaths: null,
      hospitalizedCurrently: 369,
      name: 'Kentucky',
      recovered: 2266,
    },
    {
      state: 'LA',
      deaths: 2267,
      last3daysDeaths: null,
      hospitalizedCurrently: 1333,
      name: 'Louisiana',
      recovered: 20316,
    },
    {
      state: 'MA',
      deaths: 4840,
      last3daysDeaths: null,
      hospitalizedCurrently: 3229,
      name: 'Massachusetts',
      recovered: null,
    },
    {
      state: 'MD',
      deaths: 1614,
      last3daysDeaths: null,
      hospitalizedCurrently: 1665,
      name: 'Maryland',
      recovered: 2159,
    },
    {
      state: 'ME',
      deaths: 64,
      last3daysDeaths: null,
      hospitalizedCurrently: 43,
      name: 'Maine',
      recovered: 857,
    },
    {
      state: 'MI',
      deaths: 4526,
      last3daysDeaths: null,
      hospitalizedCurrently: 1531,
      name: 'Michigan',
      recovered: 22686,
    },
    {
      state: 'MN',
      deaths: 558,
      last3daysDeaths: null,
      hospitalizedCurrently: 476,
      name: 'Minnesota',
      recovered: 6322,
    },
    {
      state: 'MO',
      deaths: 472,
      last3daysDeaths: null,
      hospitalizedCurrently: 855,
      name: 'Missouri',
      recovered: null,
    },
    {
      state: 'MP',
      deaths: 2,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Northern Mariana Islands',
      recovered: 12,
    },
    {
      state: 'MS',
      deaths: 421,
      last3daysDeaths: null,
      hospitalizedCurrently: 607,
      name: 'Mississippi',
      recovered: 4421,
    },
    {
      state: 'MT',
      deaths: 16,
      last3daysDeaths: null,
      hospitalizedCurrently: 4,
      name: 'Montana',
      recovered: 422,
    },
    {
      state: 'NC',
      deaths: 544,
      last3daysDeaths: null,
      hospitalizedCurrently: 513,
      name: 'North Carolina',
      recovered: null,
    },
    {
      state: 'ND',
      deaths: 35,
      last3daysDeaths: null,
      hospitalizedCurrently: 34,
      name: 'North Dakota',
      recovered: 762,
    },
    {
      state: 'NE',
      deaths: 92,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Nebraska',
      recovered: null,
    },
    {
      state: 'NH',
      deaths: 121,
      last3daysDeaths: null,
      hospitalizedCurrently: 112,
      name: 'New Hampshire',
      recovered: 1210,
    },
    {
      state: 'NJ',
      deaths: 9116,
      last3daysDeaths: null,
      hospitalizedCurrently: 4628,
      name: 'New Jersey',
      recovered: 15642,
    },
    {
      state: 'NM',
      deaths: 181,
      last3daysDeaths: null,
      hospitalizedCurrently: 201,
      name: 'New Mexico',
      recovered: 1189,
    },
    {
      state: 'NV',
      deaths: 301,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Nevada',
      recovered: 205,
    },
    {
      state: 'NY',
      deaths: 21271,
      last3daysDeaths: null,
      hospitalizedCurrently: 7776,
      name: 'New York',
      recovered: 57180,
    },
    {
      state: 'OH',
      deaths: 1331,
      last3daysDeaths: null,
      hospitalizedCurrently: 929,
      name: 'Ohio',
      recovered: null,
    },
    {
      state: 'OK',
      deaths: 270,
      last3daysDeaths: null,
      hospitalizedCurrently: 177,
      name: 'Oklahoma',
      recovered: 3154,
    },
    {
      state: 'OR',
      deaths: 127,
      last3daysDeaths: null,
      hospitalizedCurrently: 139,
      name: 'Oregon',
      recovered: 1125,
    },
    {
      state: 'PA',
      deaths: 3688,
      last3daysDeaths: null,
      hospitalizedCurrently: 2285,
      name: 'Pennsylvania',
      recovered: null,
    },
    {
      state: 'PR',
      deaths: 108,
      last3daysDeaths: null,
      hospitalizedCurrently: 161,
      name: 'Puerto Rico',
      recovered: null,
    },
    {
      state: 'RI',
      deaths: 418,
      last3daysDeaths: null,
      hospitalizedCurrently: 292,
      name: 'Rhode Island',
      recovered: 772,
    },
    {
      state: 'SC',
      deaths: 330,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'South Carolina',
      recovered: 4120,
    },
    {
      state: 'SD',
      deaths: 34,
      last3daysDeaths: null,
      hospitalizedCurrently: 79,
      name: 'South Dakota',
      recovered: 2125,
    },
    {
      state: 'TN',
      deaths: 242,
      last3daysDeaths: null,
      hospitalizedCurrently: null,
      name: 'Tennessee',
      recovered: 7369,
    },
    {
      state: 'TX',
      deaths: 1049,
      last3daysDeaths: null,
      hospitalizedCurrently: 1735,
      name: 'Texas',
      recovered: 20141,
    },
    {
      state: 'UT',
      deaths: 66,
      last3daysDeaths: null,
      hospitalizedCurrently: 172,
      name: 'Utah',
      recovered: 2901,
    },
    {
      state: 'VA',
      deaths: 827,
      last3daysDeaths: null,
      hospitalizedCurrently: 1593,
      name: 'Virginia',
      recovered: 3124,
    },
  ],
};
