module.exports = {
  ENUMS: {
    STATES: {
      NV: 'Nevada',
      CA: 'California',
      DE: 'Delaware',
      NH: 'New Hampshire',
      MS: 'Mississippi',
      IA: 'Iowa',
      AK: 'Alaska',
      NJ: 'New Jersey',
      AR: 'Arkansas',
      AS: 'American Samoa',
      RI: 'Rhode Island',
      TX: 'Texas',
      PR: 'Puerto Rico',
      GA: 'Georgia',
      CO: 'Colorado',
      OH: 'Ohio',
      IN: 'Indiana',
      SC: 'South Carolina',
      CT: 'Connecticut',
      NM: 'New Mexico',
      KY: 'Kentucky',
      DC: 'District Of Columbia',
      SD: 'South Dakota',
      KS: 'Kansas',
      ME: 'Maine',
      FL: 'Florida',
      GU: 'Guam',
      MI: 'Michigan',
      LA: 'Louisiana',
      OR: 'Oregon',
      AZ: 'Arizona',
      VA: 'Virginia',
      MD: 'Maryland',
      MN: 'Minnesota',
      UT: 'Utah',
      AL: 'Alabama',
      ND: 'North Dakota',
      ID: 'Idaho',
      PA: 'Pennsylvania',
      NY: 'New York',
      MO: 'Missouri',
      MP: 'Northern Mariana Islands',
      TN: 'Tennessee',
      NC: 'North Carolina',
      MT: 'Montana',
      NE: 'Nebraska',
      OK: 'Oklahoma',
      MA: 'Massachusetts',
      IL: 'Illinois',
      HI: 'Hawaii',
    },
  },
};
